export const ORDER_FOOD_CREATE_REQUEST = 'ORDER_FOOD_CREATE_REQUEST' 
export const ORDER_FOOD_CREATE_SUCCESS = 'ORDER_FOOD_CREATE_SUCCESS' 
export const ORDER_FOOD_CREATE_FAIL = 'ORDER_FOOD_CREATE_FAIL' 

export const ORDER_FOOD_DETAILS_REQUEST = 'ORDER_FOOD_DETAILS_REQUEST' 
export const ORDER_FOOD_DETAILS_SUCCESS = 'ORDER_FOOD_DETAILS_SUCCESS' 
export const ORDER_FOOD_DETAILS_FAIL = 'ORDER_FOOD_DETAILS_FAIL' 