export const ORDER_FOOD_CREATE_REQUEST = 'ORDER_FOOD_CREATE_REQUEST' 
export const ORDER_FOOD_CREATE_SUCCESS = 'ORDER_FOOD_CREATE_SUCCESS' 
export const ORDER_FOOD_CREATE_FAIL = 'ORDER_FOOD_CREATE_FAIL' 

export const ORDER_FOOD_DETAILS_REQUEST = 'ORDER_FOOD_DETAILS_REQUEST' 
export const ORDER_FOOD_DETAILS_SUCCESS = 'ORDER_FOOD_DETAILS_SUCCESS' 
export const ORDER_FOOD_DETAILS_FAIL = 'ORDER_FOOD_DETAILS_FAIL' 

export const ORDER_FOOD_PAY_REQUEST = 'ORDER_FOOD_PAY_REQUEST' 
export const ORDER_FOOD_PAY_SUCCESS = 'ORDER_FOOD_PAY_SUCCESS' 
export const ORDER_FOOD_PAY_FAIL = 'ORDER_FOOD_PAY_FAIL'
export const ORDER_FOOD_PAY_RESET = 'ORDER_FOOD_PAY_RESET'

export const ORDER_FOOD_LIST_MY_REQUEST = 'ORDER_FOOD_LIST_MY_REQUEST' 
export const ORDER_FOOD_LIST_MY_SUCCESS = 'ORDER_FOOD_LIST_MY_SUCCESS' 
export const ORDER_FOOD_LIST_MY_FAIL = 'ORDER_FOOD_LIST_MY_FAIL'
export const ORDER_FOOD_LIST_MY_RESET = 'ORDER_FOOD_LIST_MY_RESET'

export const ORDER_FOOD_LIST_REQUEST = 'ORDER_FOOD_LIST_REQUEST' 
export const ORDER_FOOD_LIST_SUCCESS = 'ORDER_FOOD_LIST_SUCCESS' 
export const ORDER_FOOD_LIST_FAIL = 'ORDER_FOOD_LIST_FAIL'

export const ORDER_FOOD_DELIVER_REQUEST = 'ORDER_FOOD_DELIVER_REQUEST' 
export const ORDER_FOOD_DELIVER_SUCCESS = 'ORDER_FOOD_DELIVER_SUCCESS' 
export const ORDER_FOOD_DELIVER_FAIL = 'ORDER_FOOD_DELIVER_FAIL'
export const ORDER_FOOD_DELIVER_RESET = 'ORDER_FOOD_DELIVER_RESET'