export const GALLERY_LIST_REQUEST = 'GALLERY_LIST_REQUEST'
export const GALLERY_LIST_SUCCESS = 'GALLERY_LIST_SUCCESS'
export const GALLERY_LIST_FAIL = 'GALLERY_LIST_FAIL'

export const GALLERY_DETAILS_REQUEST = 'GALLERY_DETAILS_REQUEST'
export const GALLERY_DETAILS_SUCCESS = 'GALLERY_DETAILS_SUCCESS'
export const GALLERY_DETAILS_FAIL = 'GALLERY_DETAILS_FAIL'

export const GALLERY_CREATE_REVIEW_REQUEST = 'GALLERY_CREATE_REVIEW_REQUEST'
export const GALLERY_CREATE_REVIEW_SUCCESS = 'GALLERY_CREATE_REVIEW_SUCCESS'
export const GALLERY_CREATE_REVIEW_FAIL = 'GALLERY_CREATE_REVIEW_FAIL'
export const GALLERY_CREATE_REVIEW_RESET = 'GALLERY_CREATE_REVIEW_RESET'